# There are lots of nice built-in themes.
# You can preview them with `:theme ` and
# cycle through them with TAB.
theme = "monokai_pro_octagon"

[editor]
# Trying out always having a bar at the top of
# the editor that shows open buffers.
bufferline = "always"
shell = ["zsh", "-c"]

[editor.cursor-shape]
# These help to clearly differentiate whether
# we're currently in normal, insert, or select
# mode. I've grown so used to this that it's
# practically manditory
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = " "

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "register", "position", "file-encoding"]

[keys.normal]
"C-," = ":config-open"

[keys.normal."space"]
"tab" = ":buffer-next"

[keys.normal.","]
"u" = ":pipe-to firefox --new-tab "

[keys.normal.","."h"]
"c" = ":open ~/.config/helix/config.toml"
"l" = ":open ~/.config/helix/languages.toml"

[keys.insert]
"C-[" = "normal_mode"
