[[language]]
name = "markdown"
text-width = 80
soft-wrap.wrap-at-text-width = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "python"
auto-format = true

[language.formatter]
command = "black"
args = ["--quiet", "-"]
